version: '2.20.2'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: djangok8:v1
    env_file:
      - web/.env
    environment:
      - PORT=8020
    ports:
      - "8080:8020"
# version: '3.9'
# services:
#     web:
#         depends_on:
#           - postgres_db
#           - redis_db
#         build:
#           context: web
#           dockerfile: Dockerfile
#         image: djangok8:v1
#         environment:
#           - PORT=8023
#         env_file:
#           - web/.env
#         ports:
#           - "8001:8023"
#         command: sh -c "chmod +x /web/migrate.sh && sh /web/migrate.sh && sh /web/entrypoint.sh"
#         volumes:
#             - staticfiles:/web/staticfiles/
#     postgres_db:
#         image: postgres
#         restart: always
#         env_file: web/.env
#         command: -p 5433
#         expose:
#           - 5433
#         ports:
#           - "5433:5433"
#         volumes: 
#             - postgres_data:/var/lib/postgresql/data/
#     redis_db:
#         image: redis
#         restart: always
#         expose:
#           - 6380
#         ports:
#           - "6380:6380"
#         volumes:
#             - redis_data:/data
#         entrypoint: redis-server --appendonly yes --port 6380

# volumes: 
#     staticfiles:
#         external: true
#     redis_data:
#     postgres_data:
